site_name: YuXian Collection 
theme:
  favicon: img/favicon.ico
  name: material
  custom_dir: overrides
  language: zh
  features:
    - content.code.annotate
    - content.action.edit
    # - navigation.sections
    - navigation.tracking
    - navigation.top
    - navigation.tabs
    - navigation.footer
    - navigation.indexes
    # - navigation.expand
    - navigation.instant
    - navigation.collapsible
    - search.suggest
    - search.share
  palette: 
    # primary: cyan

    - media: "(prefers-color-scheme: light)"
      scheme: default # 日间模式
      primary: cyan # 上方的
      accent: indigo # 链接等可交互元件的高亮色
      # teal 
      toggle:
        icon: material/toggle-switch # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - media: "(prefers-color-scheme: dark)"
      scheme: slate # 夜间模式
      primary: black 
      accent: indigo
      # teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: 切换至日间模式

nav:
  - Home: 
    - index.md
    # - 写在前言: Intro/before/index.md
    # - 学期总结: Intro/summary/index.md
    # - 草稿: Intro/caogao/index.md

  - 课程:
    - 目录: major/index.md
    - 理论力学: major/理论力学/理论力学.md
    - 材料力学: major/材料力学/材料力学.md
    - 弹性力学: major/弹性力学/弹性力学.md
    - 流体力学: major/流体力学/流体力学.md
    - 振动力学: 
      - 振动力学: major/振动力学/index.md
      - 自由振动: major/振动力学/自由振动.md
      - 单自由度振动: major/振动力学/单自由度振动.md
      - 多自由度振动: major/振动力学/多自由度振动.md
      - 连续系统振动: major/振动力学/连续系统振动.md
      - 非线性振动: major/振动力学/非线性振动.md
    - 数理方法: major/数理方法/数理方法.md
    - 科学计算导论: major/科学计算导论/科学计算导论.md
    - 计算方法: major/计算方法/计算方法.md
    - 工程热力学: major/工程热力学/工程热力学.md
    - 电工电子学及实验: major/电工电子学及实验/电工电子学及实验.md
    - 智柔体力学概论: major/智柔体力学概论.md
    - 生物力学基础: 
      - 目录: major/生物力学基础/index.md
      - 绪论: major/生物力学基础/Intro.md
      - 热力学基础: major/生物力学基础/therm.md
      - 统计力学: major/生物力学基础/statmech.md
      - 统计力学应用: major/生物力学基础/statmech II.md
    - 计算流体力学:
      - 计算流体力学: major/CFD/index.md
    #- 清代文化史: Liber/清代文化史.md
  - 自学:
    - 目录: diy/index.md
    - 24暑假课程总结: diy/暑假课程记录.md
    # - Data100: diy/Data100/Data100.md
    - 跨专业课程: diy/跨专业/跨专业.md
    - EECS498: 
      - Introduction For EECS498: diy/EECS498/index.md
      - Image Classification: diy/EECS498/Image Classification.md
      - Linear Classifier: diy/EECS498/Linear Classifier.md
      - Regularization and Optimization: diy/EECS498/Regularization and Optimization.md
      - Backpropagation: diy/EECS498/Backpropagation.md 
      - Neural Networks: diy/EECS498/Neural Network.md
      - Convolutional Networks: diy/EECS498/Convolutional Networks.md
      - CNN Architectures: diy/EECS498/CNN Architectures.md
      - Training Neural Networks Ⅰ: diy/EECS498/Training Neural Networks Ⅰ.md
      - Training Neural Networks Ⅱ: diy/EECS498/Training Neural Networks Ⅱ.md
      - CNN Architectures Ⅱ: diy/EECS498/CNN Architectures Ⅱ.md
      - Object Detection: diy/EECS498/Object Detection.md
      - Object Detectors: diy/EECS498/Object Detectors.md
      - Image Segmentation: diy/EECS498/Image Segmentation.md
      - Recurrent Networks : diy/EECS498/Recurrent Networks.md
      - Attention: diy/EECS498/Attention.md
      # - Vision Transformers: diy/EECS498/Vision Transformers.md
      
    # - CS198:
    #   - Introduction For CS198: diy/CS198/CS198.md

    - CS285:
      - Introduction For CS285: diy/CS285/index.md
      - Supervised Learning of Behaviors: diy/CS285/Supervised Learning of Behaviors.md
      - Introduction To Reinforcement Learning: diy/CS285/Introduction To Reinforcement Learning.md
      - Policy Gradients: diy/CS285/Policy Gradients.md
      - Actor-Critic Algorithms: diy/CS285/Actor-Critic Algorithms.md
            
    - Math notes: diy/Some MATH Notes.md
    
  - Miscellaneous : 
    - 目录: Miscellaneous/index.md
    - Paper: 
      - A Review of Data-Driven Discovery for Dynamics Equation: Miscellaneous/Paper/A Review of Data-Driven Discovery for Dynamics Equation.md
      - Data-Driven Identification of Parametric Partial Differential Equations: Miscellaneous/Paper/Data-Driven Identification of Parametric Partial Differential Equations.md
      - An intelligent spinal soft robot with self-sensing adaptability: Miscellaneous/Paper/An intelligent spinal soft robot with self-sensing adaptability.md
      - Stochastic First-And zeroth-Order Methods For Nonconvex Stochastic Programming: Miscellaneous/Paper/Stochastic First-And zeroth-Order Methods For Nonconvex Stochastic Programming.md
    #- 读书笔记: 
    - 一席: 
      # - About: Miscellaneous/Yixi/index.md
      - 激进的共识: Miscellaneous/Yixi/激进的共识.md
      - 一次生活和无数次生活: Miscellaneous/Yixi/一次生活和无数次生活.md  
    

copyright: Copyright &copy; 

extra: 

  generator: false
  social: 
    - icon: fontawesome/solid/paper-plane
      link: mailto:<xianyu403@gmail.com>
    - icon: fontawesome/brands/github
      link: https://github.com/Aphia-XianYu
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com
    - icon: fontawesome/solid/ghost


plugins:
  # - glightbox
  - search
  - offline

  - statistics:
      words_per_minute: 150  # 每分钟预计阅读字数
      codelines_per_minute: 80  # 每分钟预计阅读代码行数
      page_read_time: true  # 是否显示单页预计阅读时间


  - blog:
      post_date_format: full #时间
      draft: true
      draft_if_future_date: true #自动将具有未来日期的帖子标记为草稿
      post_readtime: true
      post_readtime_words_per_minute: 150  #计算帖子的阅读时间时读者每分钟预计阅读的字数
      post_url_format: "{date}/{slug}"
      # categories_slugify: !!python/object/apply:pymdownx.slugs.slugify
      #   kwds:
      #     case: lower
      # categories_toc: true
      # pagination_per_page: 5
      pagination_url_format: "page/{page}"
      authors_file: "{blog}/.authors.yml"  #作者信息

markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - def_list
  - footnotes
  - md_in_html
  - meta # 支持Markdown文件上方自定义标题标签等
  - pymdownx.caret
  - pymdownx.betterem
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format # 代码块高亮插件
  - pymdownx.arithmatex:  # latex支持
      generic: true
  - toc:
      permalink: true # 固定标题位置为当前位置
  - pymdownx.highlight: # 代码块高亮
      anchor_linenums: true
      linenums: true # 显示行号
      # auto_title: true # 显示编程语言名称
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - markdown.extensions.toc:
      slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}}
      permalink: "\ue157"
  - pymdownx.pathconverter:
      base_path: '' # default: ''
      relative_path: '' # default ''
      absolute: false # default: false
      tags: 'a script img link object embed'

extra_javascript:
  - javascripts/extra.js  #自定义javascript
  - javascripts/mathjax.js  #Latex支持
  - https://polyfill.io/v3/polyfill.min.js?features=es6   #Latex支持
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js   #Latex支持
  #  - ckplayer/js/ckplayer.js #播放器配置
  - https://cdn.jsdelivr.net/npm/gitalk@latest/dist/gitalk.min.js  #gitalk支持
  - https://cdn.jsdelivr.net/npm/mermaid@10.0.2/dist/add-html-label-6e56ed67.min.js #忘了

extra_css:
  - stylesheets/extra.css # 自定义CSS
  - stylesheets/link.css  #友链配置
  - stylesheets/customize.css
  # - stylesheets/video.css #播放器可选配置
  - https://cdn.jsdelivr.net/npm/gitalk@latest/dist/gitalk.css #gitalk支持
  # - ckplayer/css/ckplayer.css   #播放器配置
  - https://cdn.staticfile.org/font-awesome/4.7.0/css/font-awesome.css  # font-awesome表情支持
  # - https://cdnjs.cloudflare.com/ajax/libs/social-share.js/1.0.16/css/share.min.css  #分享支持

  - https://cdn.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css  #字体
  # - https://cdn.jsdelivr.net/npm/lxgw-wenkai-lite-webfont@1.1.0/style.css #字体
  # - https://cdn.jsdelivr.net/npm/lxgw-wenkai-tc-webfont@1.0.0/style.css  #字体
  # - https://cdn.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css  #字体